CREATE TABLE link (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    link TEXT NOT NULL,
    code VARCHAR(255) NOT NULL,
    ip VARCHAR(255) NOT NULL,
    hits BIGINT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);